Codificación UnitsComparatorTest.java y MyBagManager.getUnitsIterator()
MIT-FS/ShopManager pull request #75
Opened 2021-01-03 20:28 UTC by elemoncitos

Se añade la clase UnitsComparatorTest.java que prueba UnitsComparator.java.
Se añade la implementación del método MyBagManager.getUnitsIterator().

2021-01-03 20:37 UTC, eyksamech1 approved these changes

2021-01-11 08:45 UTC, MIT-FS reviewed
El método para devovler iterador me parece correcto
Has cambiado la codificación de caracteres respecto al proyecto original, por favor mantén la misma codificación de caracteres.

2021-01-11 08:53 UTC, MIT-FS requested changes
Este assert
assertTrue(result <= -1, "Se espera un número positivo (cantidad de producto 1 es mayor que la del 2)");
no parece correcto
assertTrue verifica que la expresión es cierta, es decir verifica que result es negativo... si no es negativo da error ¡¡pero tu mensaje es "se espera un número positivo"!! así que este test falla si el número es positivo y la explicación que das del fallo en el mensaje es "se espera un número positivo" ¡¡pues no tiene sentido!! si el número es postiivo por qué ha fallado si se espera un núemro positivo...
En el siguiente me pasa justo al revés
assertTrue(result >= 1, "Se espera un número negativo (cantidad de producto 2 es mayor que la del 1)");
esto falla si result es negativo, pero la explicación que das es que se esperaba un número negativo ¿por qué ha fallado si el número ha sido negativo como se esperaba?
REvísalo por favor.
De todos modos esto se supone que no es lo que tú debías entregar aquí, tú debes entregar el test para verificar el iterador (es decir tienes que entregar el código que tú has desarrollado y los test que lo prueba, que son los que ha hecho tu compañera)

2021-01-11 08:54 UTC, MIT-FS commented
La entrega no es correcta, debes entregar el código que se te asignó (el método para devolver el iterador) y el test que verifica que este código es correcto (Es decir el que codificó tu compañera)
Cuando lo reenvíes por favor pide que se fusione con la rama BagManager, no con la rama desarrollo

2021-01-11 08:54 UTC, closed without merging